---
version: "3"

services:
  xui:
    image: alireza7/x-ui
    container_name: x-ui
    hostname: yourhostname
    volumes:
      - ./db/:/etc/x-ui/
      - ./cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped
