---
version: "3"

services:
  xui:
    image: alireza7/x-ui
    container_name: x-ui
    hostname: yourhostname
    volumes:
      - /mnt/usb-d8aee58a/storage/db/:/etc/x-ui/
      - /mnt/usb-d8aee58a/storage/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped
